### ISSUE TITLE
Share link contains localhost in URL

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/Fairdrive#2]
Which cannot be right ... : 
![image](https://user-images.githubusercontent.com/1554520/94193890-35975c80-feb1-11ea-8481-6914a28ac163.png)

**Comment by crtahlin** [comment]
Also, trying to paste it, it seems to be an empty string, so I suspect link is not really copied to clipboard as stated in message.

**Comment by lucille-bellepleure** [comment]
Hmm on brave/linux the copying to clipboard works. Maybe test on diff systems? 
I have changed the hostname to env variable
