### ISSUE TITLE
Cannot add a folder with same name after deleting it

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/Fairdrive#3]
1. create a folder "Shared", cd into it
2. create subfolder "Lower1", cd into it
3. create subfolder "Lower2"
4. delete subfolder "Lower2"
5. create subfolder "Lower2" (it does not appear!)

**Comment by lucille-bellepleure** [comment]
@jmozah

**Comment by jmozah** [comment]
fixed this in commit f30548555becd57943f3cfdb3ed2d7254f32bce7

**Comment by jmozah** [comment]
@crtahlin  Please close this issue
