### ISSUE TITLE
Giving link if sharing via name not needed

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/Fairdrive#4]
Currently, if sharing a file, you have to enter a name. After entering a name, the link to file is also given. Both are not needed.

![Fairdrive-share-Peek 2020-09-24 22-18](https://user-images.githubusercontent.com/1554520/94196031-1948ef00-feb4-11ea-8206-9fb03d5b3755.gif)

There should probably either be two ways to share a file - via name and via link to send - or for starters just the link to be shared.

**Comment by lucille-bellepleure** [comment]
Leaving out name for now as it is not needed.
