### ISSUE TITLE
Editing account offers to delete it

### ISSUE THREAD

**Issue by crtahlin** [fairDataSociety/Fairdrive#5]
As visible in video:

![Fairdrive-edit-account-2020-09-24 22-27](https://user-images.githubusercontent.com/1554520/94196922-51046680-feb5-11ea-8917-d01c7c283916.gif)

After clicking "Edit account" I would expect maybe options to:
- edit avatar
- delete account

When getting message about deleting, there should be a confirm button and a cancel button.

**Comment by lucille-bellepleure** [comment]
Removing that feature as it is not there yet
